### ISSUE TITLE
Don't NAT container

### ISSUE THREAD

**Issue by agallo** [CAAREN-engineering/caida-spoofer-docker#2]
Ideally, the container would use the host's network directly, rather than work through the Docker NAT function.

**Comment by agalloGWU** [comment]
Various networking options:

bridge (default) network:
`docker run -it --rm caida-spoofer-docker:latest`

host network:
`docker run --network=host -it --rm caida-spoofer-docker:latest`

macvlan
`docker run --network=bittersweet -it --rm caida-spoofer-docker:latest`
